### ISSUE TITLE
关于贡献文档的2个问题

### ISSUE THREAD

**Issue by offline-hx** [APICloud-com/apicloud_docs#3]
1.自己fork是新建分支修改内容还是直接在fork的master分支上修改后PR  
2.有些截图因为网站改版过期了，比如APICloud>开放平台接入>支付宝的第一张大图，要更换截图应该，图片目录要怎么组织

**Comment by beiluo** [comment]
1.直接在master分支上修改即可，新建分支更多的是为了版本管理
2.截图我们会尽快替换
